/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/examples/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/examples/login`; params?: Router.UnknownInputParams; } | { pathname: `/examples/profile`; params?: Router.UnknownInputParams; } | { pathname: `/examples/quiz`; params?: Router.UnknownInputParams; } | { pathname: `/examples/wallet`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/splash`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/examples/leaderboard`; params?: Router.UnknownOutputParams; } | { pathname: `/examples/login`; params?: Router.UnknownOutputParams; } | { pathname: `/examples/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/examples/quiz`; params?: Router.UnknownOutputParams; } | { pathname: `/examples/wallet`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/sign-in${`?${string}` | `#${string}` | ''}` | `/splash${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/examples/leaderboard${`?${string}` | `#${string}` | ''}` | `/examples/login${`?${string}` | `#${string}` | ''}` | `/examples/profile${`?${string}` | `#${string}` | ''}` | `/examples/quiz${`?${string}` | `#${string}` | ''}` | `/examples/wallet${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/examples/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/examples/login`; params?: Router.UnknownInputParams; } | { pathname: `/examples/profile`; params?: Router.UnknownInputParams; } | { pathname: `/examples/quiz`; params?: Router.UnknownInputParams; } | { pathname: `/examples/wallet`; params?: Router.UnknownInputParams; };
    }
  }
}
